add factory operator script

diff --git a/auto_usb b/auto_usb
--- a/auto_usb
+++ b/auto_usb
@@ -32,3 +32,33 @@ fi
 if [ $ng_flag -ne 0 ]; then
 	exit 2
 fi
+
+echo "------------------------------"
+read -p "unplug usb and plug agaiin:" input_data
+lsusb -t > log
+str=$(cat log)
+str=$(echo $str | sed 's/ //g')  #remove spance
+echo $str > log
+#cat log
+r=$(grep -o $usb2_flag log | wc -l)
+#echo $r
+if [ $r -eq $usb2_count ]; then
+        echo "USB hub's USB2.0 ok"  [$usb2_count/$r]
+else
+        echo "USB hub's USB2.0 fail"  [$usb2_count/$r]
+        ng_flag=3
+fi
+
+r=$(grep -o $usb3_flag log | wc -l)
+#echo $r
+if [ $r -eq $usb3_count ]; then
+        echo "USB hub's USB3.0 ok" [$usb3_count/$r]
+else
+        echo "USB hub's USB3.0 fail" [$usb3_count/$r]
+        ng_flag=2
+fi
+
+if [ $ng_flag -ne 0 ]; then
+        exit 4
+fi
+
